In [1]:
import sys
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import openpyxl

print("Python:", sys.version)
print("pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("scikit-learn:", sklearn.__version__)
print("Environment ready.")

Python: 3.11.8 (main, Feb 19 2026, 01:12:21) [Clang 17.0.0 (clang-1700.6.3.2)]
pandas: 3.0.3
NumPy: 2.4.6
scikit-learn: 1.9.0
Environment ready.

## Raw Dataset Inspection

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DATA = PROJECT_ROOT / "data" / "raw" / "emails.csv"

print("Interpreter:", Path(sys.executable).name)
print("Dataset:", RAW_DATA.relative_to(PROJECT_ROOT))
print("Exists:", RAW_DATA.exists())
print("Size (GB):", round(RAW_DATA.stat().st_size / 1024**3, 2))

Interpreter: python
Dataset: data/raw/emails.csv
Exists: True
Size (GB): 1.33

### Preview the source data

In [3]:
preview = pd.read_csv(RAW_DATA, nrows=5)

print("Columns:", preview.columns.tolist())
print("Preview shape:", preview.shape)
display(preview)

Columns: ['file', 'message']
Preview shape: (5, 2)

                       file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

## Full Dataset Inventory

The raw CSV is processed in chunks to verify its size and basic quality without loading the complete dataset into memory.

In [4]:
CHUNK_SIZE = 10_000

total_rows = 0
missing_file = 0
missing_message = 0
blank_message = 0

for chunk in pd.read_csv(
    RAW_DATA,
    usecols=["file", "message"],
    chunksize=CHUNK_SIZE
):
    total_rows += len(chunk)
    missing_file += chunk["file"].isna().sum()
    missing_message += chunk["message"].isna().sum()

    blank_message += (
        chunk["message"]
        .fillna("")
        .str.strip()
        .eq("")
        .sum()
    )

inventory = {
    "total_rows": int(total_rows),
    "missing_file": int(missing_file),
    "missing_message": int(missing_message),
    "blank_message": int(blank_message),
}

inventory

{'total_rows': 517401,
 'missing_file': 0,
 'missing_message': 0,
 'blank_message': 0}

### Inventory interpretation

The raw Enron CSV contains **517,401 records**. The inspection found
**0** missing file identifiers, **0** missing messages, and
**0** blank messages. The dataset therefore requires parsing,
deduplication, and usability checks before sampling or modeling.

## Labeling Pilot

A fixed-seed random sample of 30 emails is extracted for testing the parsing and labeling procedures before creating the full 200-record labeling queue.

In [5]:
from email import policy
from email.parser import Parser

SEED = 42
PILOT_SIZE = 30

rng = np.random.default_rng(SEED)
selected_positions = set(
    rng.choice(total_rows, size=PILOT_SIZE, replace=False)
)

selected_chunks = []
row_offset = 0

for chunk in pd.read_csv(
    RAW_DATA,
    usecols=["file", "message"],
    chunksize=CHUNK_SIZE
):
    positions = np.arange(row_offset, row_offset + len(chunk))
    mask = np.isin(positions, list(selected_positions))

    if mask.any():
        selected_chunks.append(chunk.loc[mask].copy())

    row_offset += len(chunk)

pilot_raw = pd.concat(selected_chunks, ignore_index=True)

print("Pilot rows:", len(pilot_raw))

Pilot rows: 30

In [6]:
def parse_email(raw_message):
    parsed = Parser(policy=policy.default).parsestr(raw_message)

    subject = str(parsed.get("subject", "")).strip()

    try:
        if parsed.is_multipart():
            body_part = parsed.get_body(preferencelist=("plain",))
            body = body_part.get_content() if body_part else ""
        else:
            body = parsed.get_content()
    except Exception:
        body = str(parsed.get_payload())

    body = str(body).strip()
    combined_text = f"{subject}\n\n{body}".strip()

    return subject, body, combined_text


parsed_rows = []

for _, row in pilot_raw.iterrows():
    subject, body, combined_text = parse_email(row["message"])

    parsed_rows.append({
        "message_id": row["file"],
        "source_file": row["file"],
        "sampling_stratum": "random_pilot",
        "subject": subject,
        "body": body,
        "combined_text": combined_text,
        "text_length": len(combined_text),
    })

pilot = pd.DataFrame(parsed_rows)

print("Parsed pilot rows:", len(pilot))
print("Empty combined text:", pilot["combined_text"].str.strip().eq("").sum())

display(
    pilot[
        [
            "message_id",
            "subject",
            "text_length",
        ]
    ]
)

Parsed pilot rows: 30
Empty combined text: 0

,message_id,subject,text_length
0,campbell-l/inbox/592.,FW: Options Market Update,282
1,campbell-l/sent/173.,Re: Common Parts request,1175
2,cash-m/deleted_items/194.,RE: Super Saturday Questionnaire (Oct. 27) - R...,424
3,dasovich-j/all_documents/9065.,RE:,1530
4,donoho-l/inbox/junk_file/231.,Scheduled Vacation - Steve Harris,516
5,farmer-d/cornhusker/61.,REVISED-------Kleberg plant outages in Septemb...,652
6,jones-t/notes_inbox/3339.,Re: Click Paper Approvals 3/5/01 _ GCP Respons...,858
7,kaminski-v/all_documents/6148.,Re: Job description,1694
8,kaminski-v/sent/1755.,Completion of LNG Model Review,960
9,kaminski-v/universities/359.,CMU students,693
10,kean-s/all_documents/4891.,CEO Meetings,1153
11,kean-s/archiving/untitled/1973.,Re: Travel/Security Information on Japan,1114
12,kitchen-l/_americas/mrha/ooc/217.,Multimedia Harvard Cases,1197
13,lavorato-j/discussion_threads/162.,The Absolute End.....,634
14,lay-k/inbox/740.,,886
15,linder-e/all_documents/403.,Start Date: 4/12/01; HourAhead hour: 4; <CODE...,1117
16,mclaughlin-e/all_documents/577.,,153
17,mims-thurston-p/_sent_mail/279.,Re: GREETINGS!,943
18,perlingiere-d/sent_items/224.,RE: ENRON Master Gas Agreement,1781
19,ring-r/eesiisopjm/29.,New MUI User request,212
20,rogers-b/genco_jv_ipo/52.,Gas Questions,327
21,sanders-r/all_documents/263.,Nolan Deposition: Day 2,1714
22,schoolcraft-d/_sent_mail/8.,Re: Zenger-Miller Course,4380
23,scott-s/all_documents/1367.,Open Enrollment 2001,2371
24,scott-s/discussion_threads/1254.,American Airlines Net SAAver Fares,10917
25,shackleton-s/notes_inbox/886.,The New Power Company; Reserved Share Program,2195
26,shapiro-r/all_documents/1545.,Electricity traders' tech habits get scrutiny,7711
27,skilling-j/discussion_threads/153.,ENA Customer Satisfaction,1233
28,taylor-m/deleted_items/644.,Fwd: American Airlines Net SAAver Fares,15135
29,white-s/deleted_items/756.,RE: status of CCO book accounting treatment,3490

## Improve the review text

In [7]:
import re

REVIEW_LENGTH = 2_000

def normalize_review_text(text):
    text = str(text or "")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def build_review_excerpt(subject, body):
    subject = normalize_review_text(subject)
    body = normalize_review_text(body)

    review_text = f"Subject: {subject}\n\n{body}".strip()

    excerpt = review_text[:REVIEW_LENGTH]
    was_truncated = len(review_text) > REVIEW_LENGTH

    return excerpt, was_truncated


pilot[["review_excerpt", "excerpt_truncated"]] = pilot.apply(
    lambda row: pd.Series(
        build_review_excerpt(row["subject"], row["body"])
    ),
    axis=1,
)

display(
    pilot[
        [
            "message_id",
            "subject",
            "review_excerpt",
            "excerpt_truncated",
            "text_length",
        ]
    ]
)

,message_id,subject,review_excerpt,excerpt_truncated,text_length
0,campbell-l/inbox/592.,FW: Options Market Update,Subject: FW: Options Market Update\n\n-----Ori...,False,282
1,campbell-l/sent/173.,Re: Common Parts request,"Subject: Re: Common Parts request\n\nLeon, tha...",False,1175
2,cash-m/deleted_items/194.,RE: Super Saturday Questionnaire (Oct. 27) - R...,Subject: RE: Super Saturday Questionnaire (Oct...,False,424
3,dasovich-j/all_documents/9065.,RE:,Subject: RE:\n\nThanks. I'll take 12 magnums. ...,False,1530
4,donoho-l/inbox/junk_file/231.,Scheduled Vacation - Steve Harris,Subject: Scheduled Vacation - Steve Harris\n\n...,False,516
5,farmer-d/cornhusker/61.,REVISED-------Kleberg plant outages in Septemb...,Subject: REVISED-------Kleberg plant outages i...,False,652
6,jones-t/notes_inbox/3339.,Re: Click Paper Approvals 3/5/01 _ GCP Respons...,Subject: Re: Click Paper Approvals 3/5/01 _ GC...,False,858
7,kaminski-v/all_documents/6148.,Re: Job description,Subject: Re: Job description\n\n--------------...,False,1694
8,kaminski-v/sent/1755.,Completion of LNG Model Review,Subject: Completion of LNG Model Review\n\nJef...,False,960
9,kaminski-v/universities/359.,CMU students,Subject: CMU students\n\nI have given your ema...,False,693
10,kean-s/all_documents/4891.,CEO Meetings,Subject: CEO Meetings\n\nSteve -- here's the s...,False,1153
11,kean-s/archiving/untitled/1973.,Re: Travel/Security Information on Japan,Subject: Re: Travel/Security Information on Ja...,False,1114
12,kitchen-l/_americas/mrha/ooc/217.,Multimedia Harvard Cases,"Subject: Multimedia Harvard Cases\n\nKen, Jeff...",False,1197
13,lavorato-j/discussion_threads/162.,The Absolute End.....,"Subject: The Absolute End.....\n\nJohn, I apol...",False,634
14,lay-k/inbox/740.,,"Subject: \n\nMr Lay,\n\nI just wanted to thank...",False,886
15,linder-e/all_documents/403.,Start Date: 4/12/01; HourAhead hour: 4; <CODE...,Subject: Start Date: 4/12/01; HourAhead hour: ...,False,1117
16,mclaughlin-e/all_documents/577.,,"Subject: \n\nSharon,\n\nHow do I call you? Eac...",False,153
17,mims-thurston-p/_sent_mail/279.,Re: GREETINGS!,Subject: Re: GREETINGS!\n\nSo nice to hear fro...,False,943
18,perlingiere-d/sent_items/224.,RE: ENRON Master Gas Agreement,Subject: RE: ENRON Master Gas Agreement\n\nTha...,False,1781
19,ring-r/eesiisopjm/29.,New MUI User request,Subject: New MUI User request\n\nNarsimha Misr...,False,212
20,rogers-b/genco_jv_ipo/52.,Gas Questions,"Subject: Gas Questions\n\nMitch,\n\nI spoke wi...",False,327
21,sanders-r/all_documents/263.,Nolan Deposition: Day 2,Subject: Nolan Deposition: Day 2\n\nRichard: \...,False,1714
22,schoolcraft-d/_sent_mail/8.,Re: Zenger-Miller Course,Subject: Re: Zenger-Miller Course\n\nI would l...,True,4380
23,scott-s/all_documents/1367.,Open Enrollment 2001,Subject: Open Enrollment 2001\n\nOpen Enrollme...,True,2371
24,scott-s/discussion_threads/1254.,American Airlines Net SAAver Fares,Subject: American Airlines Net SAAver Fares\n\...,True,10917
25,shackleton-s/notes_inbox/886.,The New Power Company; Reserved Share Program,Subject: The New Power Company; Reserved Share...,True,2195
26,shapiro-r/all_documents/1545.,Electricity traders' tech habits get scrutiny,Subject: Electricity traders' tech habits get ...,True,7711
27,skilling-j/discussion_threads/153.,ENA Customer Satisfaction,Subject: ENA Customer Satisfaction\n\nThought ...,False,1233
28,taylor-m/deleted_items/644.,Fwd: American Airlines Net SAAver Fares,Subject: Fwd: American Airlines Net SAAver Far...,True,15135
29,white-s/deleted_items/756.,RE: status of CCO book accounting treatment,Subject: RE: status of CCO book accounting tre...,True,3490

## helper to review one complete 2,000-character excerpt at a time

In [8]:
def show_review_record(row_number):
    row = pilot.iloc[row_number]

    print("Row:", row_number)
    print("Message ID:", row["message_id"])
    print("Subject:", row["subject"])
    print("Excerpt length:", len(row["review_excerpt"]))
    print("Excerpt truncated:", row["excerpt_truncated"])
    print("\nReview excerpt:\n")
    print(row["review_excerpt"])

    if row["excerpt_truncated"]:
        print("\n[Additional message content is available.]")

## Inspect the full message on demand

In [9]:
def show_full_message(message_id):
    matches = pilot.loc[pilot["message_id"] == message_id]

    if matches.empty:
        print("Message not found.")
        return

    row = matches.iloc[0]

    print("Message ID:", row["message_id"])
    print("Subject:", row["subject"])
    print("\nBody:\n")
    print(row["body"])

## Export the Labeling Pilot

The pilot records are exported without complete message bodies. Labels are assigned manually using labeling-guide version 1.0.

In [10]:
pilot["urgency_label"] = ""
pilot["label_reason"] = ""
pilot["label_version"] = "1.0"
pilot["reviewer"] = "Keith G. Broussard"
pilot["review_status"] = "Not Reviewed"
pilot["review_notes"] = ""

pilot_export = pilot[
    [
        "message_id",
        "source_file",
        "sampling_stratum",
        "subject",
        "review_excerpt",
        "excerpt_truncated",
        "text_length",
        "urgency_label",
        "label_reason",
        "label_version",
        "reviewer",
        "review_status",
        "review_notes",
    ]
].copy()

PILOT_WORKBOOK = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "enron_urgency_labeling_pilot_v1.xlsx"
)

# Excel rejects a small set of legacy control characters found in raw Enron text.
# Remove only those forbidden characters; retain tabs, line breaks, and readable text.
EXCEL_ILLEGAL_CHARACTERS = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F]")


def make_excel_safe(value):
    if isinstance(value, str):
        return EXCEL_ILLEGAL_CHARACTERS.sub("", value)
    return value


text_columns = pilot_export.select_dtypes(include=["object", "str"]).columns
pilot_export[text_columns] = pilot_export[text_columns].map(make_excel_safe)

remaining_illegal_characters = sum(
    pilot_export[column]
    .fillna("")
    .astype(str)
    .str.contains(EXCEL_ILLEGAL_CHARACTERS)
    .sum()
    for column in text_columns
)
assert remaining_illegal_characters == 0, "Excel-forbidden characters remain."

PILOT_WORKBOOK.parent.mkdir(parents=True, exist_ok=True)
pilot_export.to_excel(
    PILOT_WORKBOOK,
    index=False,
    sheet_name="Labeling Pilot",
    freeze_panes=(1, 0),
    autofilter=True,
)

print("Pilot workbook:", PILOT_WORKBOOK.relative_to(PROJECT_ROOT))
print("Rows exported:", len(pilot_export))
print("Excel-forbidden characters remaining:", remaining_illegal_characters)

Pilot workbook: data/processed/enron_urgency_labeling_pilot_v1.xlsx
Rows exported: 30
Excel-forbidden characters remaining: 0